### PR TITLE
Issue #18 -  Feature to configure autoscaler block and attributes for spotinst-ocean-eks

### PR DESCRIPTION
**Pull request by bharatgovindaradjou**
Currently ocean-eks module defaults autoscaler configuration to automatic configuration when enabled. The autoscaler is also [enabled by default.](https://github.com/spotinst/terraform-spotinst-ocean-eks/blob/master/ocean.tf#L42,43)

```
autoscaler {
    autoscale_is_enabled     = true
    autoscale_is_auto_config = true
  }
}
```

The purpose of this issue is to add some flexibility to spotinst/ocean-eks module to make use of the ability to configure autoscaler available in the **spotinst_ocean_aws** resource.

This gives us infrastructure designers and engineers using spotinst to develop ocean clusters configurable for autoscalers' headroom, cooldown and resource limits and even pass on values to ocean's virtual node groups

```
autoscaler {
  autoscale_is_enabled     = true
  autoscale_is_auto_config = true
  auto_headroom_percentage = 100
  autoscale_cooldown       = 300

  autoscale_headroom {
    cpu_per_unit    = 1024
    gpu_per_unit    = 0
    memory_per_unit = 512
    num_of_units    = 2
  }

  autoscale_down {
    max_scale_down_percentage = 60
  }

  resource_limits {
    max_vcpu       = 1024
    max_memory_gib = 1500
  }
}
```

The following vars have been introduced that can be added to **ocean-eks** module to achieve this
```
enable_autoscaler
auto_headroom_percentage
autoscaler_cooldown
autoscaler_cpu_per_unit
autoscaler_gpu_per_unit
autoscaler_memory_per_unit
autoscaler_num_of_units
autoscaler_max_scale_down_percentage
autoscaler_max_vcpu
autoscaler_max_memory_gib
```

### CODE REVIEW

**Review by liranp — APPROVED** [review]

**Comment by liranp** [comment]
@bharatgovindaradjou I apologize for the delay in reviewing this. Your work is greatly appreciated. Can you please rebase your branch and resolve any existing conflicts before we merge it with master? Thanks.

**Comment by bharatgovindaradjou** [comment]
@liranp Thank you for the review. I have rebased from spotinst master and resolved the conflicts. Please merge at your convenience.

**Comment by bharatgovindaradjou** [comment]
@liranp Please confirm the release in which this will be included.

**Review by liranp — APPROVED** [review]

**Comment by liranp** [comment]
Thank you for your contribution, @bharatgovindaradjou. Release [v1.7.0](https://registry.terraform.io/modules/spotinst/ocean-eks/spotinst/1.7.0) is available now.

**Pull request merged**
